### ISSUE TITLE
Suggestion: Tilføj data om lektionernes generelle start-og sluttidspunkter

### ISSUE THREAD

**Issue by PeterH2N** [Lectio-Go/LibLectio#7]
![image](https://user-images.githubusercontent.com/59964273/105631351-68953100-5e4e-11eb-8974-ad7b3fbd2b92.png)
Tilføj informationerne som vist på billedet, som kommer fra lectios hjemmeside

(Jeg har ikke adgang til Kanban boardet, ellers ville jeg have lagt det der)

**Comment by mathiasgredal** [comment]
Fixed by #8
